import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatBps, formatUsd } from "@/lib/utils";
import { SIMULATION_MAX_IMPACT_BPS, type LaunchCheck, type LaunchCheckStatus, type LaunchPlan, type LaunchPlanOracleFeed } from "@elf/shared";

const CHECK_VISUAL: Record<LaunchCheckStatus, { glyph: string; className: string; label: string }> = {
  pass: { glyph: "✓", className: "text-positive", label: "Passed" },
  fail: { glyph: "✕", className: "text-negative", label: "Failed" },
  unavailable: { glyph: "?", className: "text-warning", label: "DATA UNAVAILABLE" },
  not_run: { glyph: "○", className: "text-muted-foreground", label: "Not run yet" },
};

const FEED_STATE_TEXT: Record<LaunchPlanOracleFeed["state"], string> = {
  live: "LIVE",
  entitlement_restricted: "Restricted — Pyth entitlement required",
  not_configured: "NOT CONFIGURED",
  unauthenticated: "UNAUTHENTICATED",
  rate_limited: "RATE LIMITED",
  unavailable: "UNAVAILABLE",
};

const FEED_KIND_LABEL = { equity: "Regulated equity", xstock: "xStock", ondo: "Ondo" } as const;

function formatDuration(seconds: number): string {
  if (seconds >= 86_400 && seconds % 86_400 === 0) return `${seconds / 86_400} d`;
  if (seconds >= 3_600) return `${+(seconds / 3_600).toFixed(2)} h`;
  return `${seconds} s`;
}

const pct = (n: number) => `${+n.toFixed(2)}%`;

/**
 * Renders a LaunchPlan exactly as the engines produced it. This component
 * contains no thresholds, no scoring and no data of its own; anything the
 * plan could not determine is shown as unavailable rather than filled in.
 */
export function LaunchPlanView({ plan }: { plan: LaunchPlan }) {
  const { asset, curve, profile, liquidity, trading, graduation, oracle, simulation } = plan;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <Badge variant="gold">Proposal</Badge>
        <span className="text-xs text-muted-foreground">
          Generated by ELF&rsquo;s deterministic curve compiler, simulation engine and Meteora&rsquo;s own validators — not an AI agent. Nothing is deployed.
        </span>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Generated launch plan</CardTitle>
          <span className="text-[11px] uppercase tracking-wide text-muted-foreground">{plan.engine}</span>
        </CardHeader>
        <CardContent className="grid gap-6 md:grid-cols-2">
          <Section title="Asset">
            <Row label="Name" value={`${asset.name} (${asset.symbol})`} />
            <Row label="Issuer" value={asset.issuer} />
            <Row label="Source" value={asset.source} />
            <Row label="Reference price" value={`${formatUsd(asset.referencePriceUsd)} (issuer-declared)`} />
          </Section>

          <Section title="Curve">
            <Row
              label="Configuration"
              value={
                <>
                  {curve.label} {curve.isRecommended && <Badge variant="accent" className="ml-1">Recommended</Badge>}
                </>
              }
            />
            <Row label="Initial market cap" value={formatUsd(curve.initialMarketCapUsd, { compact: true })} />
            <Row label="Migration market cap" value={formatUsd(curve.migrationMarketCapUsd, { compact: true })} />
            <Row label="Total supply" value={curve.tokenSupply.toLocaleString("en-US")} />
            <Row label="Curve starts at" value={`${formatUsd(curve.impliedStartPriceUsd)} per token`} />
            <p className="pt-1 text-[11px] leading-relaxed text-muted-foreground">{curve.rationale}</p>
          </Section>

          <Section title="Liquidity">
            <Row label="Initial liquidity" value={formatUsd(liquidity.initialLiquidityUsd)} />
            <Row label="Target liquidity" value={formatUsd(liquidity.targetLiquidityUsd)} />
            <Row label="Quote token" value={liquidity.quoteToken} />
            <Row label="Creator liquidity" value={`${pct(liquidity.creatorLiquidityPercentage)} (${pct(liquidity.creatorPermanentLockedLiquidityPercentage)} permanently locked)`} />
            <Row label="Partner liquidity" value={`${pct(liquidity.partnerLiquidityPercentage)} (${pct(liquidity.partnerPermanentLockedLiquidityPercentage)} permanently locked)`} />
          </Section>

          <Section title="Trading parameters">
            <Row label="Trading fee" value={`${formatBps(trading.startingFeeBps)} → ${formatBps(trading.endingFeeBps)}`} />
            <Row label="Fee schedule" value={`${trading.numberOfPeriods} periods over ${formatDuration(trading.totalDurationSeconds)}`} />
            <Row label="Dynamic fee" value={trading.dynamicFeeEnabled ? `On (max price change ${formatBps(trading.dynamicFeeMaxPriceChangeBps)})` : "Off"} />
            <Row label="Fees collected in" value={trading.collectFeeMode === "quote_token" ? "Quote token" : "Output token"} />
            <Row label="Expected volatility / risk profile" value={`${profile.expectedVolatility} / ${profile.riskProfile}`} />
          </Section>

          <Section title="Graduation" wide>
            <p className="text-xs leading-relaxed text-foreground">{graduation.trigger}</p>
            <Row label="Your declared target" value={formatUsd(graduation.declaredTargetUsd)} />
            <Row
              label="Threshold Meteora derives from this curve"
              value={
                graduation.derivedThresholdQuote === null
                  ? "Data unavailable"
                  : `${graduation.derivedThresholdQuote.toLocaleString("en-US", { maximumFractionDigits: 4 })} ${graduation.quoteToken}${
                      graduation.derivedThresholdUsd === null ? "" : ` (${formatUsd(graduation.derivedThresholdUsd)})`
                    }`
              }
            />
            <Row label="Migrates into" value="Meteora DAMM v2" />
            <Row label="Migration fee" value={formatBps(graduation.migrationFeeBps)} />
            <Row label="Supply at migration" value={pct(graduation.percentageSupplyOnMigration)} />
          </Section>

          <Section title="Oracle" wide>
            <Row label="Pyth status" value={oracle.headline} />
            {oracle.feeds.length === 0 ? (
              <p className="text-[11px] text-muted-foreground">{oracle.note}</p>
            ) : (
              oracle.feeds.map((f) => (
                <Row
                  key={f.feedSymbol}
                  label={`${FEED_KIND_LABEL[f.kind]} · ${f.feedSymbol}`}
                  value={f.state === "live" && f.priceUsd !== null ? `LIVE — ${formatUsd(f.priceUsd)}` : FEED_STATE_TEXT[f.state]}
                />
              ))
            )}
          </Section>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Simulation</CardTitle>
          <span className="text-[11px] uppercase tracking-wide text-muted-foreground">SIMULATED — not live data</span>
        </CardHeader>
        <CardContent>
          <p className="mb-3 text-[11px] text-muted-foreground">Simulation — no blockchain transaction is executed.</p>
          {simulation.status === "not_run" && <p className="text-xs text-muted-foreground">Not run yet. Review the plan above, then run the simulation.</p>}
          {simulation.status === "invalid" && (
            <div className="text-xs text-negative" role="alert">
              <p className="font-medium">The simulation results failed validation:</p>
              <ul className="mt-1 list-disc pl-4">{simulation.reasons.map((r) => <li key={r}>{r}</li>)}</ul>
            </div>
          )}
          {simulation.status === "completed" && (
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-left uppercase tracking-wide text-muted-foreground">
                    <th className="py-1.5 pr-3">Scenario</th>
                    <th className="py-1.5 pr-3">Worst-case price impact</th>
                    <th className="py-1.5">Unfillable trades</th>
                  </tr>
                </thead>
                <tbody>
                  {simulation.scenarios.map((s) => (
                    <tr key={s.scenario} className="border-t border-border">
                      <td className="py-1.5 pr-3 capitalize text-foreground">{s.scenario.replace(/_/g, " ")}</td>
                      <td className="py-1.5 pr-3 font-tabular">
                        {s.worstCasePriceImpactBps >= SIMULATION_MAX_IMPACT_BPS
                          ? `${SIMULATION_MAX_IMPACT_BPS.toLocaleString("en-US")} bps (100% cap — a trade could not be filled)`
                          : formatBps(s.worstCasePriceImpactBps)}
                      </td>
                      <td className="py-1.5 font-tabular">{s.unfillableTrades}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Risk &amp; validation checks</CardTitle>
          <span className="text-[11px] uppercase tracking-wide text-muted-foreground">No score — each check is pass, fail or unavailable</span>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2.5">
            {plan.checks.map((c) => (
              <CheckRow key={c.id} check={c} />
            ))}
          </ul>
        </CardContent>
      </Card>

      {plan.warnings.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Warnings</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="list-disc space-y-1.5 pl-4">
              {plan.warnings.map((w) => (
                <li key={w} className="text-xs leading-relaxed text-warning">
                  {w}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Assumptions</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="list-disc space-y-1.5 pl-4">
            {plan.assumptions.map((a) => (
              <li key={a} className="text-xs leading-relaxed text-muted-foreground">
                {a}
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}

function CheckRow({ check }: { check: LaunchCheck }) {
  const v = CHECK_VISUAL[check.status];
  return (
    <li className="flex gap-3">
      <span aria-hidden className={`mt-0.5 w-4 shrink-0 text-center font-tabular text-sm ${v.className}`}>
        {v.glyph}
      </span>
      <div className="min-w-0">
        <p className="text-xs font-medium text-foreground">
          {check.label} <span className={`ml-1 text-[10px] uppercase tracking-wide ${v.className}`}>{v.label}</span>
        </p>
        <p className="text-[11px] leading-relaxed text-muted-foreground">{check.detail}</p>
      </div>
    </li>
  );
}

function Section({ title, children, wide = false }: { title: string; children: React.ReactNode; wide?: boolean }) {
  return (
    <section className={wide ? "md:col-span-2" : undefined}>
      <h3 className="mb-2 text-[11px] font-semibold uppercase tracking-[0.15em] text-muted-foreground">{title}</h3>
      <dl className="space-y-1.5">{children}</dl>
    </section>
  );
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-4 text-xs">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-right font-tabular text-foreground">{value}</dd>
    </div>
  );
}
